_slice:
  id: cfn_trigger:backend/cloudformation/hub/oops-infrastructure.yaml:ConfigComplianceChangeRule-FindingProcessorTarget
  domain: infrastructure
  type: trigger
  source_files:
    - backend/cloudformation/hub/oops-infrastructure.yaml
  references: []
  tags: []
  referenced_by: []
element:
  id: cfn_trigger:backend/cloudformation/hub/oops-infrastructure.yaml:ConfigComplianceChangeRule-FindingProcessorTarget
  logicalId: ConfigComplianceChangeRule
  triggerType: event_pattern
  sourceType: eventbridge
  sourceRef: ConfigComplianceChangeRule
  targetRef: FindingProcessorLambda
  targetArn: '!GetAtt FindingProcessorLambda.Arn'
  eventBusName: '!Ref HubEventBus'
  eventPattern: '{"source":["aws.config","oops.spoke.config"],"detail-type":["Config Rules Compliance Change","Config Configuration Item Change"]}'
  eventSources:
    - aws.config
    - oops.spoke.config
  eventDetailTypes:
    - Config Rules Compliance Change
    - Config Configuration Item Change
  state: ENABLED
provenance:
  extracted_at: '2026-01-09T19:38:15.075Z'
  extractor: recon-cloudformation-extractor-v1
  file: backend/cloudformation/hub/oops-infrastructure.yaml
  line: 0
  language: cloudformation
  source_checksum: a1676567f2026f02261df125e5ed5f96f1ca2b46783c91a6013dea67be0a68bd
