_slice:
  id: cfn_trigger:backend/cloudformation/hub/oops-infrastructure.yaml:SpokeHeartbeatRule-SpokeHealthMonitorTarget
  domain: infrastructure
  type: trigger
  source_files:
    - backend/cloudformation/hub/oops-infrastructure.yaml
  references: []
  tags: []
  referenced_by: []
element:
  id: cfn_trigger:backend/cloudformation/hub/oops-infrastructure.yaml:SpokeHeartbeatRule-SpokeHealthMonitorTarget
  logicalId: SpokeHeartbeatRule
  triggerType: event_pattern
  sourceType: eventbridge
  sourceRef: SpokeHeartbeatRule
  targetRef: SpokeHealthMonitorLambda
  targetArn: '!GetAtt SpokeHealthMonitorLambda.Arn'
  eventBusName: '!Ref HubEventBus'
  eventPattern: '{"source":["aws.events"],"detail-type":["Scheduled Event"]}'
  eventSources:
    - aws.events
  eventDetailTypes:
    - Scheduled Event
  state: ENABLED
provenance:
  extracted_at: '2026-01-09T19:38:15.075Z'
  extractor: recon-cloudformation-extractor-v1
  file: backend/cloudformation/hub/oops-infrastructure.yaml
  line: 0
  language: cloudformation
  source_checksum: a1676567f2026f02261df125e5ed5f96f1ca2b46783c91a6013dea67be0a68bd
